<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130815184542 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
            'UPDATE category_counter dcc
              JOIN (SELECT dc.category_id
                 , count(dc.id) AS CountDemandsInCategory
            FROM
              demand_category dc
            JOIN demand d
            ON dc.demand_id = d.id
            WHERE
              d.moderated_at IS NOT NULL
            GROUP BY
              dc.category_id
            ORDER BY
              CountDemandsInCategory
              DESC) sq ON sq.category_id = dcc.category_id
            SET
              dcc.demands_count = sq.CountDemandsInCategory,
              dcc.updated_at = now()'
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
