<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130815190111 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
            'INSERT INTO category_counter (category_id, city_id)
            SELECT c.Message_ID
                 , cr.Region_ID
            FROM

              Message73 c
            JOIN Classificator_Region cr
              '
        );

        $this->addSql(
            'UPDATE category_counter dcc
            JOIN (SELECT dc.category_id, d.city_id
                       , count(dc.id) AS CountDemandsInCategory
                  FROM
                    demand_category dc
                  JOIN demand d
                  ON dc.demand_id = d.id
                  WHERE
                    d.moderated_at IS NOT NULL
                  GROUP BY
                    dc.category_id,
                    d.city_id
                  ORDER BY
                    CountDemandsInCategory
                    DESC) sq
            ON sq.category_id = dcc.category_id
              AND sq.city_id = dcc.city_id
            SET
              dcc.demands_count = sq.CountDemandsInCategory, dcc.updated_at = now()'
        );

        $this->addSql('CREATE UNIQUE INDEX UNIQ_category_city ON category_counter (category_id, city_id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
