<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130815182338 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('INSERT INTO category_counter (category_id) SELECT Message_ID FROM Message73');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
