<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130815160239 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE category_counter (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, city_id INT DEFAULT NULL, demands_count INT NOT NULL, demands_count_recursive INT NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_6FAD40612469DE2 (category_id), INDEX IDX_6FAD4068BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
