<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130827171629 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql("ALTER TABLE newsletter_recipient ADD processed_at DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE newsletter_recipient ADD CONSTRAINT FK_C5BE71C922DB1917 FOREIGN KEY (newsletter_id) REFERENCES newsletter (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
    }
}
