<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131008140934 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE UserSend SET subscribed_on_news = 1 WHERE tosend = 1 OR tosend = 2');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
