<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131021135306 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE demand SET answers_count = (SELECT COUNT(*) FROM demand_answer WHERE demand_id = demand.id) WHERE 1=1;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
