<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131018183810 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE callback (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, phone VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, callback_at DATETIME DEFAULT NULL, call_from_type INT NOT NULL, INDEX IDX_79F974264584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
