<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140805155351 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE Message75 ADD company_log_id INT DEFAULT NULL, ADD company_description_id INT DEFAULT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_8BE21763D7F839F3 ON Message75 (company_log_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_8BE217632357B9C8 ON Message75 (company_description_id)");
        $this->addSql("UPDATE Message75 SET company_description_id = Message_ID, company_log_id = Message_ID");
        $this->addSql("ALTER TABLE company_payment_details
                        ADD legal_address VARCHAR(255) DEFAULT NULL,
                        ADD mail_address VARCHAR(255) DEFAULT NULL,
                        ADD inn CHAR(11) DEFAULT NULL,
                        ADD kpp CHAR(11) DEFAULT NULL,
                        ADD orgn CHAR(11) DEFAULT NULL,
                        ADD okpo INT DEFAULT NULL,
                        ADD okved VARCHAR(255) DEFAULT NULL,
                        ADD director_full_name VARCHAR(255) DEFAULT NULL,
                        ADD bank_title VARCHAR(255) DEFAULT NULL,
                        ADD bank_bik INT DEFAULT NULL,
                        ADD bank_account CHAR(30) DEFAULT NULL,
                        ADD bank_correspondent_account CHAR(30) DEFAULT NULL
        ");
        $this->addSql("UPDATE company_payment_details, Message75
                        SET
                          company_payment_details.legal_address = Message75.company_legal_adres,
                          company_payment_details.mail_address = Message75.company_mail_adress,
                          company_payment_details.inn = Message75.company_inn,
                          company_payment_details.kpp = Message75.company_kpp,
                          company_payment_details.orgn = Message75.company_ogrn,
                          company_payment_details.bank_title = Message75.company_bank,
                          company_payment_details.bank_bik = Message75.company_bik,
                          company_payment_details.bank_account = Message75.company_rs,
                          company_payment_details.bank_correspondent_account = Message75.company_cor_bill,
                          company_payment_details.okpo = Message75.company_okpo,
                          company_payment_details.okved = Message75.company_okved,
                          company_payment_details.director_full_name = Message75.company_head
                        WHERE company_payment_details.company_id = Message75.Message_ID");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
