<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140806164340 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE User ADD country_id INT NOT NULL');

        $this->addSql('CREATE INDEX IDX_2DA17977F92F3E70 ON User (country_id)');

        $this->addSql('UPDATE User u INNER JOIN Message75 c ON u.ConnectCompany = c.Message_ID SET u.city_id = c.company_city, u.country_id = c.country_id');

        $this->addSql('UPDATE User u INNER JOIN Classificator_Region cr ON u.city_id = cr.Region_ID SET u.country_id = cr.country_id WHERE u.ConnectCompany IS NULL AND cr.country_id IS NOT NULL');

        $this->addSql('UPDATE User SET country_id = 165 WHERE ConnectCompany IS NULL AND country_id = 0');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
