<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140821182610 extends AbstractMigration
{
    public function up(Schema $schema)
    {
       $this->addSql("DROP TABLE IF EXISTS counter_category_city, counter_category_country, counter_city, counter_country");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
