<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140806133426 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE Message75 CHANGE LastUpdated LastUpdated TIMESTAMP, CHANGE company_type company_type tinyint(4) DEFAULT NULL, CHANGE company_name title varchar(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE Message75
                          DROP Subdivision_ID,
                          DROP Sub_Class_ID,
                          DROP Priority,
                          DROP Keyword,
                          DROP TimeToDelete,
                          DROP TimeToUncheck,
                          DROP Parent_Message_ID,
                          DROP company_email,
                          DROP company_last_name,
                          DROP company_first_name,
                          DROP StatusMod,
                          DROP CheckDate,
                          DROP archive,
                          DROP rating,
                          DROP ratingUpdated,
                          DROP company_phone,
                          DROP company_adress,
                          DROP deleted_at
                      ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
