<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140804151711 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Message75 com JOIN Classificator_Region c
          ON com.company_city = c.Region_ID
          SET com.company_region = c.parent
          WHERE com.company_region IS NULL
          ');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
