<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140805130718 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE company_log
            (
                company_id INT NOT NULL,
                created_by INT NOT NULL,
                updated_by INT DEFAULT NULL,
                ip CHAR(15) NOT NULL,
                last_ip CHAR(15) DEFAULT NULL,
                user_agent VARCHAR(255) NOT NULL,
                last_user_agent VARCHAR(255) NOT NULL,
                INDEX IDX_8BCCECADDE12AB56 (created_by),
                INDEX IDX_8BCCECAD16FE72E1 (updated_by),
                PRIMARY KEY(company_id)
            ) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");

        $this->addSql("ALTER TABLE company_log
                        ADD CONSTRAINT FK_8BCCECAD979B1AD6
                        FOREIGN KEY (company_id)
                        REFERENCES Message75 (Message_ID)");

        $this->addSql("CREATE TABLE company_description
        (
            company_id INT NOT NULL,
            description LONGTEXT NOT NULL,
            PRIMARY KEY(company_id)
         ) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");

        $this->addSql("ALTER TABLE company_description
                         ADD CONSTRAINT FK_7435F8BE979B1AD6
                         FOREIGN KEY (company_id)
                         REFERENCES Message75 (Message_ID)");

        $this->addSql(
            "INSERT INTO company_log (company_id, created_by, updated_by, ip, user_agent, last_ip, last_user_agent)
              SELECT
                Message_ID,
                User_ID,
                LastUser_ID,
                IFNULL(IP, ''),
                IFNULL(UserAgent,''),
                IFNULL(LastIP,''),
                IFNULL(LastUserAgent,'')
              FROM Message75"
        );

        $this->addSql(
            "INSERT INTO company_description (company_id, description)
                  SELECT
                    Message_ID,
                    IFNULL(company_about, '')
                  FROM Message75"
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
