<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140807181341 extends AbstractMigration
{
    public function up(Schema $schema)
    {
       $this->addSql("
            ALTER TABLE Message73 DROP new_parent_id, DROP Section_ID, DROP metalspros_slug,
            DROP slug_combined_spros
       ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
