<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140806122725 extends AbstractMigration
{
    public function up(Schema $schema)
    {
       $this->addSql("
       ALTER TABLE Message75
            DROP User_ID,
            DROP IP,
            DROP UserAgent,
            DROP LastUser_ID,
            DROP LastIP,
            DROP LastUserAgent,
            DROP company_about,
            DROP company_legal_adres,
            DROP company_mail_adress,
            DROP company_inn,
            DROP company_kpp,
            DROP company_ogrn,
            DROP company_bank,
            DROP company_bik,
            DROP company_rs,
            DROP company_cor_bill,
            DROP company_okpo,
            DROP company_okved,
            DROP company_head
       ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
