<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140805110452 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE Message75 ADD is_slug_changed TINYINT(1) DEFAULT 0 NOT NULL');

        $this->addSql('CREATE TABLE company_old_slug (company_id INT NOT NULL, old_slug VARCHAR(255) DEFAULT NULL, PRIMARY KEY(company_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');

        $this->addSql('INSERT INTO company_old_slug VALUE(2044039, "mirovaa-metallurgia")');

        $this->addSql('UPDATE Message75 SET is_slug_changed = 1 WHERE Message_ID = 2044039');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
