<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140805175413 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE Message75 com JOIN Classificator_Region c
            ON com.company_city = c.Region_ID
            SET com.country_id = c.country_id
            WHERE c.country_id IS NOT NULL
        ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
