imports:
    - { resource: config_prod.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing/routing_%hostname_package_routing%_profiler.yml"
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
