<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140701223805 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('
            ALTER TABLE Message142
              DROP COLUMN LastUserAgent,
              DROP INDEX Company_ID_3,
              DROP INDEX Group_ID,
              DROP INDEX Sub_Class_ID_2,
              CHANGE COLUMN Name Name VARCHAR(255) NOT NULL AFTER Message_ID,
              CHANGE COLUMN Memo Memo VARCHAR(255) DEFAULT NULL AFTER Name;
        ');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
