<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140716163010 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
        CREATE TABLE
        menu_item_closure
        (id INT AUTO_INCREMENT NOT NULL,
        ancestor INT NOT NULL,
        descendant INT NOT NULL,
        depth INT NOT NULL,
        INDEX IDX_3C585A20B4465BB (ancestor),
        INDEX IDX_3C585A209A8FAD16 (descendant),
        INDEX IDX_644BC6ACFAEED5D2 (depth),
        UNIQUE INDEX IDX_CD9B0E72DCC14062 (ancestor, descendant),
        PRIMARY KEY(id))
        DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
        ");

        $this->addSql("
        CREATE TABLE
        menu_item
        (id INT AUTO_INCREMENT NOT NULL,
        parent INT DEFAULT NULL,
        mode TINYINT(1) NOT NULL,
        category_id INT DEFAULT NULL,
        title VARCHAR(255) NOT NULL,
        position INT NOT NULL,
        INDEX IDX_D754D5503D8E604F (parent),
        INDEX IDX_D754D55012469DE2 (category_id),
        PRIMARY KEY(id))
        DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
        ");

        $this->addSql("ALTER TABLE menu_item_closure ADD CONSTRAINT FK_3C585A20B4465BB FOREIGN KEY (ancestor) REFERENCES menu_item (id);");
        $this->addSql("ALTER TABLE menu_item_closure ADD CONSTRAINT FK_3C585A209A8FAD16 FOREIGN KEY (descendant) REFERENCES menu_item (id);");
        $this->addSql("ALTER TABLE menu_item ADD CONSTRAINT FK_D754D5503D8E604F FOREIGN KEY (parent) REFERENCES menu_item (id);");
        $this->addSql("ALTER TABLE menu_item ADD CONSTRAINT FK_D754D55012469DE2 FOREIGN KEY (category_id) REFERENCES Message73 (Message_ID) ON DELETE CASCADE;");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
