<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140722120252 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $resEmpty = $this->connection->fetchAll('SELECT `User_ID`, `ConnectCompany` FROM `User` WHERE `Email`=""');
        foreach ($resEmpty as $empty) {
            $sql = 'UPDATE `User` SET `Email`= ? WHERE `User_ID`= ?';
            $this->connection->executeUpdate($sql, array($empty['User_ID'].'@change-metalloprokat.ru', $empty['User_ID']));

            $sql = 'UPDATE `Message75` SET `ReplicationStatus`= ?, `inCrm`= ? WHERE `Message_ID`= ?';
            $this->connection->executeUpdate($sql, array(1, 1, $empty['ConnectCompany']));
        }

        $resDouble = $this->connection->fetchAll('SELECT u1.User_ID, u1.Email, u1.Login, u1.LastUpdated, u1.ConnectCompany, u2.ConnectCompany as comp2
                        FROM `User` u1
                        JOIN User u2 ON u1.Email = u2.Email
                        WHERE u1.`LastUpdated` < u2.`LastUpdated`');
        foreach ($resDouble as $val) {
            $sql = 'UPDATE `User` SET `Email`= ? WHERE `User_ID`= ?';
            $this->connection->executeUpdate($sql, array($val['User_ID'].'@change-metalloprokat.ru', $val['User_ID']));

            $sql = 'UPDATE `Message75` SET `ReplicationStatus`= ?, `inCrm`= ? WHERE `Message_ID`= ?';
            $this->connection->executeUpdate($sql, array(1, 1, $val['ConnectCompany']));

            $sql = 'UPDATE `Message75` SET `ReplicationStatus`= ?, `inCrm`= ? WHERE `Message_ID`= ?';
            $this->connection->executeUpdate($sql, array(1, 1, $val['comp2']));
        }

        $resDouble = $this->connection->fetchAll('SELECT u1.User_ID, u1.Email, u1.Login, u1.LastUpdated, u1.ConnectCompany, u2.ConnectCompany as comp2
                        FROM `User` u1
                        JOIN User u2 ON u1.Email = u2.Email
                        WHERE u1.`User_ID` < u2.`User_ID`');
        foreach ($resDouble as $val) {
            $sql = 'UPDATE `User` SET `Email`= ? WHERE `User_ID`= ?';
            $this->connection->executeUpdate($sql, array($val['User_ID'].'@change-metalloprokat.ru', $val['User_ID']));

            $sql = 'UPDATE `Message75` SET `ReplicationStatus`= ?, `inCrm`= ? WHERE `Message_ID`= ?';
            $this->connection->executeUpdate($sql, array(1, 1, $val['ConnectCompany']));

            $sql = 'UPDATE `Message75` SET `ReplicationStatus`= ?, `inCrm`= ? WHERE `Message_ID`= ?';
            $this->connection->executeUpdate($sql, array(1, 1, $val['comp2']));
        }

        $this->addSql('ALTER TABLE `User`
                          DROP INDEX `Email`,
                          ADD UNIQUE (`Email`);
                      ');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
