<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140715141828 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("TRUNCATE TABLE `category_test_item`");

        $this->addSql("ALTER TABLE `category_test_item`
                        ADD `size` VARCHAR( 255 ) NULL AFTER `category`,
                        ADD `mark_id` INT NULL ,
                        ADD `gost_id` INT NULL ,
                        ADD `size_id` INT NULL ,
                        ADD `class_id` INT NULL ,
                        ADD `type_id` INT NULL ,
                        ADD `vid_id` INT NULL ;");

        $resCat = $this->connection->fetchAll("select distinct(Category_ID) cat from Message142 m142 join Message73 m73 on m73.Message_ID=m142.Category_ID and cat_parent!=0 where m142.Checked=1 order by Category_ID limit 0,1000");
        foreach($resCat as $key => $val){
            $sql = 'INSERT INTO category_test_item (title, category, size, mark_id, gost_id, size_id, class_id, type_id, vid_id)
                    (SELECT DISTINCT (Name), Category_ID, Memo, m159.GostM_ID AS par1, m1592.GostM_ID AS par2, m1593.GostM_ID AS par3, m1594.GostM_ID AS par4, m1595.GostM_ID AS par5, m1596.GostM_ID AS par6
                    FROM `Message142` m142
                    LEFT JOIN Message159 m159 ON m159.Price_ID = m142.Message_ID AND m159.Type =1
                    LEFT JOIN Message159 m1592 ON m1592.Price_ID = m142.Message_ID AND m1592.Type =2
                    LEFT JOIN Message159 m1593 ON m1593.Price_ID = m142.Message_ID AND m1593.Type =3
                    LEFT JOIN Message159 m1594 ON m1594.Price_ID = m142.Message_ID AND m1594.Type =4
                    LEFT JOIN Message159 m1595 ON m1595.Price_ID = m142.Message_ID AND m1595.Type =5
                    LEFT JOIN Message159 m1596 ON m1596.Price_ID = m142.Message_ID AND m1596.Type =6
                    WHERE Category_ID='.$val["cat"].' AND m142.Checked=1 ORDER BY rand()  LIMIT 20)';
            $this->addSql($sql);

        }



    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
