<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Metal\CategoriesBundle\Entity\MenuItem;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140729125225 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE menu_item SET mode = :mode WHERE mode = :reference_mode AND id >= :id",
            array(
                'mode' => MenuItem::MODE_ADDITIONAL_REFERENCE,
                'reference_mode' => MenuItem::MODE_REFERENCE,
                'id' => 1062
            )
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
