<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141103125421 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $companySites = $this->connection->executeQuery('SELECT Message_ID as id, company_url as url FROM Message75');
        $this->connection->getConfiguration()->setSQLLogger(null);

        foreach ($companySites as $site) {
            $jsonString = json_encode($site['url'] && (mb_strlen($site['url']) < 255) ? array($site['url']) : array());
            $this->addSql('UPDATE Message75 SET company_url = :json WHERE Message_ID = :id',
                array('json' => $jsonString, 'id' => $site['id']));
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
