<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141021095017 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE Message75 AS company
                          JOIN Classificator_Region AS city ON city.Region_ID = company.company_city
                        SET company.country_id = city.country_id
                        WHERE city.country_id != company.country_id");

        $this->addSql("UPDATE User AS u
                          JOIN Message75 AS c ON u.ConnectCompany = c.Message_ID
                        SET u.country_id = c.country_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
