<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141027164759 extends AbstractMigration
{
    public function up(Schema $schema)
    {

        $this->addSql('UPDATE territorial_structure SET parent = NULL WHERE parent IN (
            SELECT t.id FROM (SELECT ts.id FROM territorial_structure AS ts WHERE federal_district_id IN (10, 11, 12)) AS t
        )');

        $this->addSql('DELETE FROM territorial_structure WHERE federal_district_id IN (10, 11, 12)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
