<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141024154506 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("ALTER TABLE `product_attribute` DROP FOREIGN KEY `FK_94DA597665A22152`");
        $this->addSql("ALTER TABLE `product_attribute` ADD CONSTRAINT `FK_94DA597665A22152` FOREIGN KEY ( `attribute_value_id` )
            REFERENCES `attribute_value` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT ;");
        $this->addSql("ALTER TABLE `product_attribute` ADD FOREIGN KEY ( `product_id` )
            REFERENCES `Message142` (`Message_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT ;");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
