<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141030161926 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // подписываем пользователей с компанией
        $this->addSql('
        INSERT IGNORE INTO UserSend (user_id, Email, subscribed_for_demands, Created, Updated)
          SELECT u.User_ID, u.Email, 1, NOW(), NOW()
          FROM User AS u LEFT JOIN UserSend AS us ON u.User_ID = us.user_id
          WHERE us.user_id IS NULL AND u.ConnectCompany IS NOT NULL;
        ');
        // и пользователей без компаний
        $this->addSql('
        INSERT IGNORE INTO UserSend (user_id, Email, subscribed_for_demands, Created, Updated)
          SELECT u.User_ID, u.Email, 0, NOW(), NOW()
          FROM User AS u LEFT JOIN UserSend AS us ON u.User_ID = us.user_id
          WHERE us.user_id IS NULL AND u.ConnectCompany IS NULL;
        ');

        // связываем подписчиков с пользователями по их имейлу
        $this->addSql('
            UPDATE
            UserSend as us
            JOIN (
                 SELECT u.User_ID, u.Email
                 FROM User AS u LEFT JOIN UserSend AS us ON u.User_ID = us.user_id
                 WHERE us.user_id IS NULL
              ) AS sub on us.Email = sub.Email
            SET us.user_id = sub.User_ID
        ');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
