<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Metal\AnnouncementsBundle\Entity\ZoneStatus;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141009134221 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DELETE FROM announcement_zone_status WHERE status = :purchased', array('purchased' => ZoneStatus::STATUS_PURCHASED));
        $this->addSql('
            INSERT INTO announcement_zone_status (announcement_id, status, starts_at, ends_at, zone_id, company_id)
            SELECT a.id, :purchased, a.starts_at, a.ends_at, z.id, a.company_id
            FROM announcement a
            JOIN announcement_zone z ON a.zone_id = z.id AND a.is_payed = TRUE
        ', array('purchased' => ZoneStatus::STATUS_PURCHASED)
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
