<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141023185145 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE territorial_structure ADD parent INT DEFAULT NULL, ADD country_id INT NOT NULL');
        $this->addSql('CREATE INDEX IDX_1A83148F3D8E604F ON territorial_structure (parent)');
        $this->addSql('CREATE INDEX IDX_1A83148FF92F3E70 ON territorial_structure (country_id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
