<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141022122008 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            CREATE TABLE attribute_value_category_friend_category
            (attribute_value_category_id INT NOT NULL, category_id INT NOT NULL, flag TINYINT(2) NOT NULL, priority SMALLINT NOT NULL,
            INDEX IDX_EA8D2CE112469DE2 (category_id), UNIQUE INDEX UNIQ_attribute_value_category_category (attribute_value_category_id, category_id),
            PRIMARY KEY(attribute_value_category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB"
        );
        $this->addSql("
            CREATE TABLE attribute_value_category_friend
            (attribute_value_category_id INT NOT NULL, attribute_value_category_friend_id INT NOT NULL, flag TINYINT(2) NOT NULL, priority SMALLINT NOT NULL,
            INDEX IDX_5701A8D18D286381 (attribute_value_category_id), INDEX IDX_5701A8D1FBD39C17 (attribute_value_category_friend_id),
            UNIQUE INDEX UNIQ_attribute_value_category_friend (attribute_value_category_id, attribute_value_category_friend_id),
            PRIMARY KEY(attribute_value_category_id, attribute_value_category_friend_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB"
        );
        $this->addSql("ALTER TABLE attribute_value_category_friend_category ADD CONSTRAINT FK_EA8D2CE18D286381 FOREIGN KEY (attribute_value_category_id) REFERENCES attribute_value_category (id)");
        $this->addSql("ALTER TABLE attribute_value_category_friend ADD CONSTRAINT FK_5701A8D18D286381 FOREIGN KEY (attribute_value_category_id) REFERENCES attribute_value_category (id)");
        $this->addSql("ALTER TABLE attribute_value_category_friend ADD CONSTRAINT FK_5701A8D1FBD39C17 FOREIGN KEY (attribute_value_category_friend_id) REFERENCES attribute_value_category (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
