<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141017123020 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE product_attribute (attribute_value_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_94DA597665A22152 (attribute_value_id), INDEX IDX_94DA59764584665A (product_id), PRIMARY KEY(attribute_value_id, product_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE attribute_value_category (id INT AUTO_INCREMENT NOT NULL, attribute_value_id INT NOT NULL, category_id INT NOT NULL, friends_data VARCHAR(8000) NOT NULL, regex_match VARCHAR(1000) DEFAULT NULL, regex_exclude VARCHAR(1000) DEFAULT NULL, INDEX IDX_7668C36065A22152 (attribute_value_id), INDEX IDX_7668C36012469DE2 (category_id), UNIQUE INDEX UNIQ_attribute_value_category (attribute_value_id, category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE attribute_value (id INT AUTO_INCREMENT NOT NULL, attribute_id INT NOT NULL, value VARCHAR(100) NOT NULL, url_priority SMALLINT NOT NULL, output_priority SMALLINT NOT NULL, slug VARCHAR(100) NOT NULL, regex_match VARCHAR(1000) DEFAULT NULL, regex_exclude VARCHAR(1000) DEFAULT NULL, additional_info VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_FE4FBB82989D9B62 (slug), INDEX IDX_FE4FBB82B6E62EFA (attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE attribute (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(100) NOT NULL, code VARCHAR(20) NOT NULL, url_priority SMALLINT NOT NULL, output_priority SMALLINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA597665A22152 FOREIGN KEY (attribute_value_id) REFERENCES attribute (id)");
        $this->addSql("ALTER TABLE attribute_value_category ADD CONSTRAINT FK_7668C36065A22152 FOREIGN KEY (attribute_value_id) REFERENCES attribute_value (id)");
        $this->addSql("ALTER TABLE attribute_value ADD CONSTRAINT FK_FE4FBB82B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
