<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141029123745 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        #Меняем местами столбцы
        $this->addSql("ALTER TABLE product_attribute MODIFY COLUMN `attribute_value_id` int(11) NOT NULL AFTER product_id");

        $this->addSql("ALTER TABLE attribute_value_category DROP friends_data");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
