<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141029143750 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $arrChange = array(670 => 'size-6.5',
            1308 => 'gost-14162-79',
            1872 => 'mark-brazh-mtc10-3-1.5',
            1859 => 'mark-brazhnmtc9-4-4-1',
            1861 => 'mark-brkmtc3-1',
            1870 => 'mark-brazhnmtc8.5-4-5-1.5',
            1884 => 'mark-brotc4-3',
            2597 => 'mark-vt-1',
            2616 => 'mark-ot-4',
            3286 => 'mark-hn70yu',
            3266 => 'mark-83nf'
        );

        foreach ($arrChange as $key => $val) {
            $this->addSql('UPDATE Message155 SET slug = :newSlug WHERE Message_ID = :id',
                array('newSlug' => $val, 'id' => $key));
        }

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
