<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140619115651 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("update company_minisite set background_color = '#d3e7f5' where background_color = '#b4cadb'");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
