<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140625160204 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        /* Create tables */
        $this->addSql("
            CREATE TABLE product_description (
              product_id INT NOT NULL,
              description VARCHAR(5000) NOT NULL DEFAULT '',
              PRIMARY KEY (product_id)
            )
              DEFAULT CHARACTER SET utf8
              COLLATE utf8_unicode_ci
              ENGINE = InnoDB
        ");

        $this->addSql("
            CREATE TABLE product_log (
              product_id INT NOT NULL,
              created_by INT NOT NULL,
              updated_by INT DEFAULT NULL,
              ip CHAR(15) NOT NULL DEFAULT '',
              user_agent VARCHAR(255) NOT NULL DEFAULT '',
              last_ip CHAR(15) DEFAULT NULL DEFAULT '',
              last_user_agent VARCHAR(255) NOT NULL DEFAULT '',
              INDEX IDX_6F103CDADE12AB56 (created_by),
              INDEX IDX_6F103CDA16FE72E1 (updated_by),
              PRIMARY KEY(product_id)
            )
              DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
        ");

        /* Transfer data */
        $this->addSql(
            'INSERT INTO product_log (product_id, created_by, updated_by, ip, user_agent, last_ip, last_user_agent)
                  SELECT
                    Message_ID,
                    User_ID,
                    LastUser_ID,
                    IP,
                    UserAgent,
                    LastIP,
                    LastUserAgent
                  FROM Message142'
        );

        $this->addSql(
            'INSERT INTO product_description (product_id, description)
                  SELECT
                    Message_ID,
                    Descr
                  FROM Message142'
        );

        /* Message142 change/remove/add column */
        $this->addSql('
                ALTER TABLE Message142
                DROP IP,
                DROP User_ID,
                DROP LastUser_ID,
                DROP UserAgent,
                DROP LastIP,
                DROP Descr,
                ADD product_description_id INT DEFAULT NULL,
                ADD product_log_id INT DEFAULT NULL,
                CHANGE Pts Pts TINYINT UNSIGNED,
                DROP Subdivision_ID,
                DROP Sub_Class_ID,
                DROP Keyword,
                DROP TimeToDelete,
                DROP TimeToUncheck,
                DROP Parent_Message_ID,
                DROP Price_min,
                DROP GOST,
                DROP Mark,
                DROP Comments;
                CREATE UNIQUE INDEX UNIQ_D373210B881B1C22 ON Message142 (product_log_id);
                CREATE UNIQUE INDEX UNIQ_D373210B5EF6E847 ON Message142 (product_description_id)
               '
        );

        $this->addSql('UPDATE Message142 SET product_description_id = Message_ID, product_log_id = Message_ID');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
