<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140619111057 extends AbstractMigration
{
    public function up(Schema $schema)
    {

        $this->addSql('ALTER TABLE Message142 MODIFY LastUpdated TIMESTAMP');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
