<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140611130746 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
            'ALTER TABLE Message75 ADD title_order_priority INT DEFAULT 0 NOT NULL, ADD normalized_title VARCHAR(255) NOT NULL'
        );
        $this->addSql('CREATE INDEX IDX_normalized_title ON Message75 (normalized_title)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
