<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140620113814 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE UserSend ADD task_hash CHAR(20) DEFAULT NULL, ADD task_hash_created_at DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_task_hash ON UserSend (task_hash)');
        $this->addSql('CREATE INDEX IDX_task_hash_created_at ON UserSend (task_hash_created_at)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
