<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140613181555 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE Classificator_FO ADD country_id INT NOT NULL');
        $this->addSql('CREATE INDEX IDX_B0BCD964F92F3E70 ON Classificator_FO (country_id)');

        $this->addSql('UPDATE Classificator_FO SET country_id = 165 WHERE FO_ID < 8');
        $this->addSql('UPDATE Classificator_FO SET country_id = 19 WHERE FO_ID = 11');
        $this->addSql('UPDATE Classificator_FO SET country_id = 83 WHERE FO_ID = 12');
        $this->addSql('UPDATE Classificator_FO SET country_id = 209 WHERE FO_ID = 10');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
