<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140624144941 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
            'UPDATE company_counter AS cc
              join Message75 AS c ON c.Message_ID = cc.company_id
            SET cc.products_updated_at = c.Created
            WHERE cc.all_products_count = 0'
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
