<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131225184456 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DROP INDEX UNIQ_user_view_date ON stats_element');
        $this->addSql('ALTER TABLE stats_element ADD item_hash VARCHAR(40) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8FA1F6419882643 ON stats_element (item_hash)');


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
