<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131219194128 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE complaint ADD city_id INT NOT NULL');
        $this->addSql('ALTER TABLE callback ADD city_id INT NOT NULL');
        $this->addSql('ALTER TABLE company_review ADD city_id INT NOT NULL');
        $this->addSql('CREATE INDEX IDX_5F2732B58BAC62AF ON complaint (city_id)');
        $this->addSql('CREATE INDEX IDX_79F974268BAC62AF ON callback (city_id)');
        $this->addSql('CREATE INDEX IDX_44DCE5B38BAC62AF ON company_review (city_id)');

        $this->addSql('UPDATE complaint SET city_id = 1123');
        $this->addSql('UPDATE callback SET city_id = 1123');
        $this->addSql('UPDATE company_review SET city_id = 1123');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
