<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131225172818 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('TRUNCATE TABLE stats_element');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_user_view_date ON stats_element (company_id, date_created_at, action, user_agent, ip)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
