<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131230150057 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE stats_product_changes (
        id INT AUTO_INCREMENT NOT NULL,
        product_id INT NOT NULL,
        company_id INT NOT NULL,
        date_created_at DATE NOT NULL,
        is_added TINYINT(1) NOT NULL,
        INDEX IDX_BAE14E254584665A (product_id),
        INDEX IDX_BAE14E25979B1AD6 (company_id),
        UNIQUE INDEX UNIQ_product_changes (company_id, date_created_at, product_id),
        PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
