<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131223162853 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE stats_city ADD reviews_phones_count SMALLINT DEFAULT '0' NOT NULL, ADD website_visits_count SMALLINT DEFAULT '0' NOT NULL, ADD reviews_products_count SMALLINT DEFAULT '0' NOT NULL");
        $this->addSql("ALTER TABLE stats_daily ADD reviews_phones_count SMALLINT DEFAULT '0' NOT NULL, ADD website_visits_count SMALLINT DEFAULT '0' NOT NULL, ADD reviews_products_count SMALLINT DEFAULT '0' NOT NULL");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
