<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131220154910 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE demand SET phone = CONCAT(phone_code, phone)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
