<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131223182009 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE stats_element (id INT AUTO_INCREMENT NOT NULL, city_id INT NOT NULL, user_id INT DEFAULT NULL, action SMALLINT NOT NULL, source_type_id SMALLINT NOT NULL, object_id INT NOT NULL, ip VARCHAR(25) NOT NULL, user_agent VARCHAR(255) NOT NULL, referer VARCHAR(255) DEFAULT NULL, session_id VARCHAR(64) DEFAULT NULL, created_at DATETIME NOT NULL, date_created_at DATE NOT NULL, INDEX IDX_D8FA1F648BAC62AF (city_id), INDEX IDX_D8FA1F64A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB"
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
