<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131224183446 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE stats_daily ADD demands_views_count SMALLINT NOT NULL,
                      ADD demands_to_favorite_count SMALLINT NOT NULL, ADD demands_answers_count SMALLINT NOT NULL;');
        $this->addSql('ALTER TABLE stats_city ADD demands_views_count SMALLINT NOT NULL,
                      ADD demands_to_favorite_count SMALLINT NOT NULL, ADD demands_answers_count SMALLINT NOT NULL;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
