<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131225114654 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE stats_daily CHANGE demands_count demands_count SMALLINT DEFAULT 0,
                        CHANGE demands_processed_count demands_processed_count SMALLINT DEFAULT 0,
                        CHANGE callback_count callback_count SMALLINT DEFAULT 0,
                        CHANGE callbacks_processed_count callbacks_processed_count SMALLINT DEFAULT 0,
                        CHANGE reviews_count reviews_count SMALLINT DEFAULT 0,
                        CHANGE complaints_count complaints_count SMALLINT DEFAULT 0,
                        CHANGE complaints_processed_count complaints_processed_count SMALLINT DEFAULT 0,
                        CHANGE demands_views_count demands_views_count SMALLINT DEFAULT 0,
                        CHANGE demands_to_favorite_count demands_to_favorite_count SMALLINT DEFAULT 0,
                        CHANGE demands_answers_count demands_answers_count SMALLINT DEFAULT 0;');

        $this->addSql('ALTER TABLE stats_city CHANGE demands_count demands_count SMALLINT DEFAULT 0,
                        CHANGE demands_processed_count demands_processed_count SMALLINT DEFAULT 0,
                        CHANGE callback_count callback_count SMALLINT DEFAULT 0,
                        CHANGE callbacks_processed_count callbacks_processed_count SMALLINT DEFAULT 0,
                        CHANGE reviews_count reviews_count SMALLINT DEFAULT 0,
                        CHANGE complaints_count complaints_count SMALLINT DEFAULT 0,
                        CHANGE complaints_processed_count complaints_processed_count SMALLINT DEFAULT 0,
                        CHANGE demands_views_count demands_views_count SMALLINT DEFAULT 0,
                        CHANGE demands_to_favorite_count demands_to_favorite_count SMALLINT DEFAULT 0,
                        CHANGE demands_answers_count demands_answers_count SMALLINT DEFAULT 0;');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
