<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131220172705 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DROP INDEX IDX_6C376A746E3618DA ON stats_city');
        $this->addSql('DROP INDEX UNIQ_comp_date_city ON stats_city');
        $this->addSql('ALTER TABLE stats_city CHANGE company_city city_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_6C376A748BAC62AF ON stats_city (city_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_comp_date_city ON stats_city (company_id, date, city_id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
