#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Debug\Debug;

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);
http_response_code(500);

if (function_exists('pinba_script_name_set')) {
    $_argv = $_SERVER['argv'];
    $_argv[0] = '/'.basename($_argv[0]);
    pinba_script_name_set(implode(' ', $_argv));
}

if (function_exists('pinba_hostname_set')) {
    pinba_hostname_set('+console.prod');
}

/**
 * @var Composer\Autoload\ClassLoader $loader
 */
$loader = require __DIR__.'/autoload.php';

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$hostnamePackage = $input->getParameterOption(array('--hostname-package'), isset($hostnamePackage) ? $hostnamePackage : 'metalloprokat');
$kernel = new AppKernel($env, $debug, $hostnamePackage);
$application = new Application($kernel);
$application->getDefinition()->addOption(new InputOption('--hostname-package', null, InputOption::VALUE_OPTIONAL));
$application->setAutoExit(false);
$exitCode = $application->run($input);

http_response_code($exitCode > 0 ? 500 : 200);
exit($exitCode);
