<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140314193052 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DROP INDEX IDX_company_caller ON callback;');
        $this->addSql('CREATE INDEX IDX_company_caller ON callback (company_id, processed_by)');
        $this->addSql('ALTER TABLE demand_item CHANGE volume volume NUMERIC(10, 2) DEFAULT NULL, CHANGE volume_type volume_type INT DEFAULT NULL');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
