<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140321172216 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("INSERT INTO mini_site_cover(id, company_id, mime_type, file_size, file_path, file_original_name, created_at, updated_at) VALUES (50, null, 'image/jpeg', 1285, 'transparent-cover.png', 'transparent-cover.png', '2014-03-21 14:44:22.0', '2014-03-21 14:44:22.0')");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
