<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140303182602 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE mini_site_cover (
        id INT AUTO_INCREMENT NOT NULL,
        company_id INT DEFAULT NULL,
        mime_type VARCHAR(255) NOT NULL,
        file_size INT NOT NULL,
        file_path VARCHAR(255) NOT NULL,
        file_original_name VARCHAR(255) NOT NULL,
        created_at DATETIME NOT NULL,
        INDEX IDX_4B18D342979B1AD6 (company_id),
        PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
