<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140326164308 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE announcement ADD fallback_file_size INT DEFAULT NULL, ADD fallback_file_path VARCHAR(255) DEFAULT NULL, ADD fallback_file_original_name VARCHAR(255) DEFAULT NULL, ADD fallback_mime_type VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
