<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140331134640 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE counter_country CHANGE min_price min_price INT DEFAULT 0 NOT NULL;');
        $this->addSql('ALTER TABLE counter_category_city CHANGE category_id category_id INT NOT NULL, CHANGE city_id city_id INT NOT NULL, CHANGE min_price min_price INT DEFAULT 0 NOT NULL;');
        $this->addSql('ALTER TABLE counter_category_country CHANGE category_id category_id INT NOT NULL, CHANGE country_id country_id INT NOT NULL, CHANGE min_price min_price INT DEFAULT 0 NOT NULL;');
        $this->addSql('ALTER TABLE counter_city CHANGE min_price min_price INT DEFAULT 0 NOT NULL;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
