<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130625150156 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Message73 SET has_siblings = 1');
        $this->addSql('UPDATE Message73 SET has_siblings = 0 WHERE Message_ID IN ( SELECT sq.id FROM ( SELECT c.Message_ID AS id FROM Message73 c JOIN Message73 p ON p.Message_ID = c.cat_parent WHERE NOT EXISTS ( SELECT cc.Message_ID FROM Message73 cc WHERE cc.cat_parent = c.cat_parent AND cc.Message_ID != c.Message_ID ) ) AS sq )');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
