login:
    path:   /login
    host: %host_prefix%%base_host%
    defaults:  { _controller: MetalUsersBundle:Security:login }

login_check:
    host: %host_prefix%%base_host%
    path: /login_check

logout:
    path: /logout
    host: %host_prefix%%base_host%
