<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130425132833 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DROP INDEX IDX_428D797312469DE2 ON demand');
        $this->addSql('ALTER TABLE demand DROP category_id');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
