<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130417145516 extends AbstractMigration
{
    public function up(Schema $schema)
    {
     $this->addSql('CREATE UNIQUE INDEX UNIQ_user_demand ON favorite (user_id, demand_id)');
     $this->addSql('CREATE UNIQUE INDEX UNIQ_user_product ON favorite (user_id, product_id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
