<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130415162733 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE demand (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, company_id INT DEFAULT NULL, body LONGTEXT NOT NULL, deadline INT NOT NULL, demand_type_id INT NOT NULL, region INT NOT NULL, company_title VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, person VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, city_id INT NOT NULL, category INT NOT NULL, spros_type INT NOT NULL, time_to_show INT NOT NULL, consumer_type INT NOT NULL, conditions LONGTEXT NOT NULL, info LONGTEXT NOT NULL, INDEX IDX_428D7973A76ED395 (user_id), INDEX IDX_428D7973979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demand_item (id INT AUTO_INCREMENT NOT NULL, demand_id INT NOT NULL, title LONGTEXT NOT NULL, volume VARCHAR(255) NOT NULL, volume_type INT NOT NULL, INDEX IDX_C1D985585D022E59 (demand_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE demand_item ADD CONSTRAINT FK_C1D985585D022E59 FOREIGN KEY (demand_id) REFERENCES demand (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED95D022E59 FOREIGN KEY (demand_id) REFERENCES demand (id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
