<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130418172837 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(
            'ALTER TABLE demand
            ADD ip VARCHAR(25) DEFAULT NULL,
            ADD user_agent VARCHAR(255) DEFAULT NULL, 
            ADD created_at DATETIME NOT NULL, 
            ADD updated_at DATETIME NOT NULL, 
            ADD updated_by INT DEFAULT NULL, 
            ADD last_ip VARCHAR(25) DEFAULT NULL, 
            ADD last_user_agent VARCHAR(255) DEFAULT NULL, 
            ADD address LONGTEXT DEFAULT NULL'
            );
        
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
