<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130409132545 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED98950F82B');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED98950F82B FOREIGN KEY (favorite_company_id) REFERENCES favorite_company (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
