<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130425190320 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE demand_answer (id INT AUTO_INCREMENT NOT NULL, demand_id INT NOT NULL, user_id INT DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, phone_code VARCHAR(10) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, description LONGTEXT NOT NULL, INDEX IDX_AA28DF8C5D022E59 (demand_id), INDEX IDX_AA28DF8CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');   
        $this->addSql('ALTER TABLE demand_answer ADD CONSTRAINT FK_AA28DF8C5D022E59 FOREIGN KEY (demand_id) REFERENCES demand (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
