<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130408190343 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");


        $this->addSql("CREATE TABLE favorite_company (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, company_id INT NOT NULL, created_at DATETIME NOT NULL, comment LONGTEXT DEFAULT NULL, INDEX IDX_12EBA721A76ED395 (user_id), INDEX IDX_12EBA721979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");

        $this->addSql("DROP INDEX IDX_68C58ED9979B1AD6 ON favorite");
        $this->addSql("ALTER TABLE favorite DROP comment, CHANGE company_id favorite_company_id INT NOT NULL");
        $this->addSql("ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED98950F82B FOREIGN KEY (favorite_company_id) REFERENCES favorite_company (id)");
        $this->addSql("CREATE INDEX IDX_68C58ED98950F82B ON favorite (favorite_company_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

    }
}
