<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140120102109 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE stats_category (id INT AUTO_INCREMENT NOT NULL,
                        category_id INT DEFAULT NULL,
                        company_id INT NOT NULL,
                        date DATE NOT NULL,
                        demands_count SMALLINT DEFAULT '0' NOT NULL,
                        demands_processed_count SMALLINT DEFAULT '0' NOT NULL,
                        callback_count SMALLINT DEFAULT '0' NOT NULL,
                        callbacks_processed_count SMALLINT DEFAULT '0' NOT NULL,
                        reviews_count SMALLINT DEFAULT '0' NOT NULL,
                        complaints_count SMALLINT DEFAULT '0' NOT NULL,
                        reviews_phones_count SMALLINT DEFAULT '0' NOT NULL,
                        website_visits_count SMALLINT DEFAULT '0' NOT NULL,
                        reviews_products_count SMALLINT DEFAULT '0' NOT NULL,
                        complaints_processed_count SMALLINT DEFAULT '0' NOT NULL,
                        demands_views_count SMALLINT DEFAULT '0' NOT NULL,
                        demands_to_favorite_count SMALLINT DEFAULT '0' NOT NULL,
                        demands_answers_count SMALLINT DEFAULT '0' NOT NULL,
                        INDEX IDX_130F8EC912469DE2 (category_id),
                        INDEX IDX_130F8EC9979B1AD6 (company_id),
                        UNIQUE INDEX UNIQ_comp_date_category (company_id, date, category_id),
                        PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
