<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140104200121 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE company_counter
            CHANGE reviews_count reviews_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE all_products_count all_products_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE new_complaints_count new_complaints_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE new_demands_count new_demands_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE new_company_reviews_count new_company_reviews_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE new_callbacks_count new_callbacks_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE employees_count employees_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE branches_count branches_count SMALLINT DEFAULT 0 NOT NULL
        ');
        $this->addSql('ALTER TABLE user_counter
            CHANGE favorite_company_count favorite_company_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE favorite_product_count favorite_product_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE favorite_demand_count favorite_demand_count SMALLINT DEFAULT 0 NOT NULL,
            CHANGE new_moderator_answers new_moderator_answers SMALLINT DEFAULT 0 NOT NULL
        ');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
