<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140122160721 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('TRUNCATE stats_element');
        $this->addSql('ALTER TABLE stats_element ADD category_id INT DEFAULT NULL');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
