<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140113174310 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE stats_day CHANGE COLUMN `year_month` year__month MEDIUMINT DEFAULT '0' NOT NULL, CHANGE COLUMN year_week year__week MEDIUMINT DEFAULT '0' NOT NULL, CHANGE COLUMN id id INT(11) NOT NULL AUTO_INCREMENT FIRST");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
