<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140124144726 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('TRUNCATE TABLE stats_category');
        $this->addSql('DROP INDEX UNIQ_comp_date_category ON stats_category');
        $this->addSql('ALTER TABLE stats_category ADD aggregation_column INT NOT NULL, ADD source_type_id SMALLINT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_comp_date_aggregation ON stats_category (company_id, date, aggregation_column)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
