<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130524122519 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE demand_item ADD category_id INT NOT NULL, CHANGE volume volume NUMERIC(10, 2) NOT NULL');
        $this->addSql('CREATE INDEX IDX_C1D9855812469DE2 ON demand_item (category_id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
