<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130528181602 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE demand_subscription ADD referer VARCHAR(255) DEFAULT NULL, ADD ip VARCHAR(25) DEFAULT NULL, ADD user_agent VARCHAR(255) DEFAULT NULL, ADD confirmation_code VARCHAR(30) DEFAULT NULL, ADD confirmed_at DATETIME DEFAULT NULL');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
