<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131125183012 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('
        ALTER TABLE Message73 ADD title_ablative VARCHAR(100) DEFAULT NULL,
        CHANGE title_genitive title_genitive VARCHAR(100) DEFAULT NULL,
        CHANGE title_accusative title_accusative VARCHAR(100) DEFAULT NULL,
        CHANGE title_prepositional title_prepositional VARCHAR(100) DEFAULT NULL
        ');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
