<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106140506 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE company_review ADD viewed_by INT DEFAULT NULL, DROP answered_at, ADD viewed_at DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_44DCE5B399D97A03 ON company_review (viewed_by)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
