<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131119164029 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('
            insert ignore into company_attribute (company_id, type)
            select distinct Company_ID, 2 from Message142 where Category_ID = 206 OR P_Category_ID = 206');

        $this->addSql('
            insert ignore into company_attribute (company_id, type)
            select distinct Company_ID, 3 from Message142 where Category_ID = 204 OR P_Category_ID = 204');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
