<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131115134950 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE callback ADD called_by INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_79F9742650E2D103 ON callback (called_by)');
        $this->addSql('CREATE INDEX IDX_company_viewer_processed ON complaint (company_id, viewed_by, processed_at)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
