<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131108181802 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE demand_answer SET created_at = :now', array('now' => date('Y-m-d H:i:s')));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
