<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131119154146 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE User ADD skype VARCHAR(50) DEFAULT NULL, ADD phone VARCHAR(50) DEFAULT NULL, ADD additional_code VARCHAR(50) DEFAULT NULL, CHANGE Icq Icq VARCHAR(12) DEFAULT NULL');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
