<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131106195017 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE demand ADD product_id INT DEFAULT NULL, ADD demand_type INT NOT NULL, ADD viewed_at DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_428D79734584665A ON demand (product_id)');
        $this->addSql('UPDATE demand SET demand_type = 1');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
