<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140417124319 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Classificator_Country SET support_phone = NULL WHERE Country_ID NOT IN (:countryIds)', array('countryIds' => 165));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
