<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Metal\ServicesBundle\Entity\AgreementTemplate;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140415171409 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $contactContent = <<<HTML
<div class="contact-wrapper clearfix">
    <div class="contact-left float-left">
        <p class="big-phone">+7 495 984-06-52</p>
        <ul class="contacts clearfix">
            <li class="item first float-left">
                <div class="head-title">
                    <strong>Наш адрес</strong>
                </div>
                <p>Москва, Большая Никитская, 22/2</p>
            </li>
            <li class="item float-left">
                <div class="head-title">
                    <strong>Адрес для бухгалтерии</strong>
                </div>
                <p>123308, г.Москва, ОПС № 308, а/я 29</p>
            </li>
            <li class="item float-left">
                <div class="head-title">
                    <strong>Электронная почта</strong>
                </div>
                <a class="mail-link" href="mailto:info@metalloprokat.ru">info@metalloprokat.ru</a>
            </li>
        </ul>
        <div class="btn-wrapper">
            <a class="js-popup-opener send-button button red-bg ie-radius ie-radius" href="#" data-popup="#feedback-popup">Написать письмо</a>
        </div>
    </div>
    <div class="map-wrapper is-bordered float-right">
        <div class="heading clearfix">
            <a class="link float-right" href="{{ brouzie_helper('MetalTerritorialBundle:Map').getYandexUrl(55.757308499276, 37.603077236508, 'Москва, Большая Никитская, 22/2') }}">Открыть в Яндекс.Картах</a>
        </div>
        <div class="map">
            <div id="branch-office-map-1123" style="width: 298px; height: 251px;"
                    class="js-map-with-placemark"
                    data-placemark="[55.757308499276, 37.603077236508]"
                    data-placemark-title="Москва, Большая Никитская, 22/2"
                    ></div>
        </div>
    </div>
</div>
HTML;

        $this->addSql('UPDATE agreement_template SET `content` = :content WHERE id = :id', array('content' => $contactContent, 'id' => AgreementTemplate::CORP_CONTACTS));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
