<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140415093759 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE counter_category_country CHANGE COLUMN category_id category_id SMALLINT(6) UNSIGNED NOT NULL, CHANGE COLUMN country_id country_id SMALLINT(6) UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE counter_category_city CHANGE COLUMN category_id category_id SMALLINT(6) UNSIGNED NOT NULL, CHANGE COLUMN city_id city_id SMALLINT(6) UNSIGNED NOT NULL');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
