<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140925182000 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, always_available, number, priority) VALUES ('Премиум', 'premium', 960, 90, 20000, 1, 1, 1, 1);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 1', 'products-content-1', 735, 80, 25000, 2, 6, 6);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 2', 'products-content-2', 735, 80, 20000, 2, 7, 7);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 3', 'products-content-3', 735, 80, 18000, 2, 8, 8);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 4', 'products-content-4', 735, 80, 16000, 2, 9, 9);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 5', 'products-content-5', 735, 80, 14000, 2, 10, 10);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 6', 'products-content-6', 735, 80, 12000, 2, 11, 11);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 7', 'products-content-7', 735, 80, 10000, 2, 12, 12);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 1', 'demands-content-1', 735, 80, 25000, 3, 6, 6);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 2', 'demands-content-2', 735, 80, 20000, 3, 7, 7);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 3', 'demands-content-3', 735, 80, 18000, 3, 8, 8);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 4', 'demands-content-4', 735, 80, 16000, 3, 9, 9);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 5', 'demands-content-5', 735, 80, 14000, 3, 10, 10);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 6', 'demands-content-6', 735, 80, 12000, 3, 11, 11);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Центральный 7', 'demands-content-7', 735, 80, 10000, 3, 12, 12);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Скроллер 1', 'left-sidebar', 150, 610, 45000, 1, 2, 2);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Скроллер 2', 'right-sidebar-1', 150, 300, 35000, 1, 3, 3);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Скроллер 3', 'right-sidebar-2', 150, 150, 20000, 1, 4, 4);
            INSERT INTO announcement_zone (title, slug, width, height, cost, section_id, number, priority) VALUES ('Скроллер 4', 'right-sidebar-3', 150, 150, 20000, 1, 5, 5);
        ");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
