<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140901151631 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('INSERT INTO company_delivery_city (company_id, city_id, kind, is_main_office, created_at, updated_at, phone, adress, address_new)
            SELECT c.Message_ID, c.company_city, 0, 1, now(), now(), c.phones_as_string, c.address_new, c.address_new
            FROM Message75 c
            WHERE NOT EXISTS (
            SELECT cd.id
            FROM company_delivery_city cd
            WHERE cd.company_id = c.Message_ID AND cd.city_id = c.company_city
  )');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
