<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140923171909 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE territorial_structure ADD title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE territorial_structure DROP INDEX IDX_1A83148FD23A6183, ADD UNIQUE INDEX UNIQ_1A83148FD23A6183 (federal_district_id)');
        $this->addSql('ALTER TABLE territorial_structure DROP INDEX IDX_1A83148F98260155, ADD UNIQUE INDEX UNIQ_1A83148F98260155 (region_id)');
        $this->addSql('ALTER TABLE territorial_structure DROP INDEX IDX_1A83148F8BAC62AF, ADD UNIQUE INDEX UNIQ_1A83148F8BAC62AF (city_id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
