<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140929155123 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql(' UPDATE announcement
SET zone_type = 101 WHERE zone_type = 1');
        $this->addSql('UPDATE announcement
SET zone_type = 102 WHERE zone_type = 2');
        $this->addSql('UPDATE announcement
SET zone_type = 103 WHERE zone_type = 3');
        $this->addSql('UPDATE announcement
SET zone_type = 104 WHERE zone_type = 4');
        $this->addSql('UPDATE announcement
SET zone_type = 105 WHERE zone_type = 5');
        $this->addSql('UPDATE announcement
SET zone_type = 106 WHERE zone_type = 6');
        $this->addSql('UPDATE announcement
SET zone_type = 107 WHERE zone_type = 7');
        $this->addSql('UPDATE announcement
SET zone_type = 108 WHERE zone_type = 8');
        $this->addSql('UPDATE announcement
SET zone_type = 116 WHERE zone_type = 9');
        $this->addSql('UPDATE announcement
SET zone_type = 117 WHERE zone_type = 10');
        $this->addSql('UPDATE announcement
SET zone_type = 118 WHERE zone_type = 11');
        $this->addSql('UPDATE announcement
SET zone_type = 119 WHERE zone_type = 12');
        $this->addSql('UPDATE announcement
SET zone_type = zone_type - 100');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
