<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140915163036 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DROP INDEX IDX_9966BAC232FD9503 ON demand_subscription_territorial');
        $this->addSql('DROP INDEX IDX_9966BAC26E3618DA ON demand_subscription_territorial');
        $this->addSql('ALTER TABLE demand_subscription_territorial ADD region_id INT DEFAULT NULL, ADD city_id INT DEFAULT NULL, DROP company_region, DROP company_city');
        $this->addSql('CREATE INDEX IDX_9966BAC298260155 ON demand_subscription_territorial (region_id)');
        $this->addSql('CREATE INDEX IDX_9966BAC28BAC62AF ON demand_subscription_territorial (city_id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
