<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140908165023 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE Message142 AS p SET p.Price = p.Price * -1 WHERE p.Price < 0");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
