<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140929131755 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE announcement_order (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, starts_at DATETIME NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(120) DEFAULT NULL, email VARCHAR(255) NOT NULL, create_announcement TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_97D8BF4FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
