<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140903123750 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE company_delivery_city SET is_main_office = 0;');
        $this->addSql('UPDATE company_delivery_city cd
            JOIN Message75 com ON com.company_city = cd.city_id AND com.Message_ID = cd.company_id
            SET cd.is_main_office = 1;
        ');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
