<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140923134228 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('TRUNCATE TABLE demand_subscription_territorial');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_user_territorial_structure ON demand_subscription_territorial (user_id, territorial_structure_id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
