<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140909123241 extends AbstractMigration
{
    public function up(Schema $schema)
    {
      $this->addSql("UPDATE Message75
                    SET latitude = null,
                    longitude = null,
                    address_new = ''
                    WHERE
                   (LENGTH(address_new) < 5 OR
                   (address_new REGEXP '^(км\.?|улица|ул\.?)?[\s+]?[0-9]+$'
                   OR address_new REGEXP '^[*-]+$'
                   OR address_new REGEXP '^http\:\/\/[a-z\.]+$'
                   OR address_new REGEXP '^россия$'))");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
