<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140915163040 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE territorial_structure (id INT AUTO_INCREMENT NOT NULL, federal_district_id INT DEFAULT NULL, region_id INT DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_1A83148FD23A6183 (federal_district_id), INDEX IDX_1A83148F98260155 (region_id), INDEX IDX_1A83148F8BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
