<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140925181959 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE announcement_zone (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(100) NOT NULL, number INT NOT NULL, slug VARCHAR(50) DEFAULT NULL, priority INT NOT NULL, width INT NOT NULL, height INT NOT NULL, cost INT NOT NULL, section_id INT NOT NULL, always_available TINYINT(1) DEFAULT '0' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8CDAC85B989D9B62 ON announcement_zone (slug)');
        $this->addSql("CREATE TABLE announcement_zone_status (id INT AUTO_INCREMENT NOT NULL, zone_id INT NOT NULL, comment VARCHAR(255) DEFAULT NULL, status SMALLINT NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, INDEX IDX_3A90CD709F2C3FAB (zone_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
