<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140915133829 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('DROP INDEX IDX_9966BAC2F92F3E70 ON demand_subscription_territorial');
        $this->addSql('ALTER TABLE demand_subscription_territorial CHANGE country_id federal_district_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_9966BAC2D23A6183 ON demand_subscription_territorial (federal_district_id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
