<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140912171436 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE TABLE demand_subscription_territorial (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, country_id INT DEFAULT NULL, company_region INT DEFAULT NULL, company_city INT DEFAULT NULL, INDEX IDX_9966BAC2A76ED395 (user_id), INDEX IDX_9966BAC2F92F3E70 (country_id), INDEX IDX_9966BAC232FD9503 (company_region), INDEX IDX_9966BAC26E3618DA (company_city), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
