<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140924131148 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE redirect SET redirect_from = '#(.+)?\\/sort\\/shpuntlarcena\\/(.+)?#ui', redirect_to = '$1/sort/spunt/spunt-larsena/$2' WHERE id = 1;");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
