<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140929112339 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $this->addSql("DROP TABLE IF EXISTS
                Stats_Attendance, Stats_Browser, Stats_Geo, Stats_IP, Stats_IP2Country, Stats_Log, Stats_OS, Stats_Phrases, Stats_Popularity, Stats_Referer, stats4price_daily,
                stats4price_daily_tmp, statEstimate, Message75i, Message142_new, Message143_old1, Message83_new, mail_queue_seq, mail_queue, MailTmp, bbb, LeftMenu,
                SrchBann_Banners, SrchBann_Campaigns, SrchBann_Clicks, SrchBann_Directories, SrchBann_Shows, SrchBann_ShowsFull, SrchBann_Shows_o");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
