<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130701144649 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Message73 SET is_enabled_metalspros = 1');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
