<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130711122724 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE demand_view (id INT AUTO_INCREMENT NOT NULL, demand_id INT NOT NULL, user_id INT DEFAULT NULL, viewed_at DATETIME NOT NULL, INDEX IDX_203F0BC85D022E59 (demand_id), INDEX IDX_203F0BC8A76ED395 (user_id), UNIQUE INDEX UNIQ_demand_category (demand_id, user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE demand_view ADD CONSTRAINT FK_203F0BC85D022E59 FOREIGN KEY (demand_id) REFERENCES demand (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
