<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130710125941 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('CREATE TABLE demand_complaint (id INT AUTO_INCREMENT NOT NULL, demand_id INT NOT NULL, user_id INT DEFAULT NULL, body LONGTEXT DEFAULT NULL, ip VARCHAR(25) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, complaint_type INT NOT NULL, INDEX IDX_486F2CE65D022E59 (demand_id), INDEX IDX_486F2CE6A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE demand_complaint ADD CONSTRAINT FK_486F2CE65D022E59 FOREIGN KEY (demand_id) REFERENCES demand (id) ON DELETE CASCADE');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
