<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130704131909 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE demand SET ip = last_ip, user_agent = last_user_agent');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
