<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Metal\ProjectBundle\Entity\ValueObject\SiteSourceTypeProvider;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140526181854 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE site ADD source_type INT NOT NULL');
        $this->addSql("UPDATE site SET source_type = :source_type_id WHERE hostname LIKE '%metalloprokat%'",
             array('source_type_id' => SiteSourceTypeProvider::SOURCE_PORTAL)
            );
        $this->addSql("UPDATE site SET source_type = :source_type_id WHERE hostname LIKE '%metalspros%'",
            array('source_type_id' => SiteSourceTypeProvider::SOURCE_SPROS)
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
