<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140526185625 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE site ADD city_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_694309E48BAC62AF ON site (city_id)');
        $this->addSql("UPDATE site s JOIN Classificator_Region c ON SUBSTRING_INDEX(s.hostname, '.', 1) = c.Keyword SET s.city_id = c.Region_ID");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
