<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140515191603 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE UserSend CHANGE subscribed_for_demands subscribed_for_demands TINYINT(1) DEFAULT '0' NOT NULL");
        $this->addSql('UPDATE UserSend SET subscribed_for_demands = false');
        $this->addSql('UPDATE UserSend SET subscribed_for_demands = true WHERE tosend = 2');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
