<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140516165356 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE company_review cr SET moderated_by = (SELECT m.User_ID from Message75 m WHERE m.Message_ID = cr.company_id), moderated_at = viewed_at WHERE viewed_at IS NOT NULL');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
