<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140515184717 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
        ALTER TABLE UserSend CHANGE is_subscription subscribed_for_demands TINYINT(1) DEFAULT '1' NOT NULL,
        CHANGE is_unsubscription deleted TINYINT(1) DEFAULT '0' NOT NULL");

        $this->addSql('UPDATE UserSend SET subscribed_for_demands = true WHERE tosend = 2');
        $this->addSql('UPDATE UserSend SET deleted = true WHERE tosend = 0');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
