<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Metal\ProductsBundle\Entity\Product;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140512111805 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Message142 SET Price = :price WHERE Price = 0', array('price' => Product::PRICE_CONTRACT));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
