<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140513182642 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE demand_item SET category_id = 516 WHERE category_id IN (1066, 1067);');
        $this->addSql('UPDATE demand SET category_id = 516 WHERE category_id IN (1066, 1067);');
        $this->addSql('UPDATE demand_item SET category_id = 38 WHERE category_id = 1065;');
        $this->addSql('UPDATE demand SET category_id = 38 WHERE category_id = 1065;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
