<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140530160640 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE Message75 ADD deleted_at DATETIME DEFAULT NULL, ADD deleted_at_ts SMALLINT DEFAULT "0" NOT NULL, DROP deletedAt');
        $this->addSql('DROP INDEX UNIQ_slug ON Message75');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_slug_deleted_at_ts ON Message75 (slug, deleted_at_ts)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
