<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140522152018 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Message75 c SET c.User_ID = 0 WHERE NOT EXISTS (SELECT * FROM User u WHERE c.User_ID = u.User_ID)');
        $this->addSql('UPDATE Message75 c JOIN (SELECT sq.User_ID, sq.ConnectCompany FROM (SELECT u.User_ID, u.ConnectCompany FROM User u ORDER BY u.Created) AS sq GROUP BY sq.ConnectCompany) author ON author.ConnectCompany = c.Message_ID SET c.User_ID = author.User_ID WHERE c.User_ID = 0');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
