<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140527192018 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE announcement ADD zone_type INT NOT NULL');
        $this->addSql('
            UPDATE announcement SET zone_type = 1
            WHERE is_payed = 1
            AND NOW() BETWEEN starts_at AND ends_at'
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
