<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140514171016 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE Message73 SET allow_products = 0, Checked=1 WHERE Message_ID IN (1066, 1067, 1065);');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
