<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140515181327 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
        ALTER TABLE UserSend ADD is_subscription TINYINT(1) DEFAULT '1' NOT NULL,
        ADD is_unsubscription TINYINT(1) DEFAULT '0' NOT NULL");

        $this->addSql('UPDATE UserSend SET is_subscription = true WHERE tosend = 1 OR tosend = 2');
        $this->addSql('UPDATE UserSend SET is_unsubscription = true WHERE tosend = 0');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
