<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140519191000 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE UserSend ADD demand_subscription_id INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_584A8FD4881B1141 ON UserSend (demand_subscription_id)');
        $this->addSql('
            INSERT INTO UserSend (Email, subscribed_for_demands)
            (SELECT email, true FROM demand_subscription WHERE unsubscribed_at IS NULL)
            ON DUPLICATE KEY UPDATE subscribed_for_demands = 1
                     ');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
