<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140530183124 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('INSERT IGNORE INTO UserSend (User_ID, Email) (SELECT User_ID, Email FROM User)');
        $this->addSql('UPDATE UserSend us JOIN User u ON us.Email = u.Email SET us.User_ID = u.User_ID');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
