<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130916151532 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE user_counter DROP INDEX UNIQ_user');
        $this->addSql('ALTER TABLE user_counter ADD UNIQUE UNIQ_992F8A72A76ED395 (user_id)');
        $this->addSql('ALTER TABLE user_counter ADD COLUMN updated_at DATETIME NOT NULL');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
