<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140214180849 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE Classificator_Region ADD administrative_center INT DEFAULT NULL');
        $this->addSql('
  UPDATE Classificator_Region cr
    JOIN (
           SELECT jcr.Regions_ID, jcr.Capital
           FROM Classificator_Regions AS jcr
         ) AS tmp ON tmp.Regions_ID = cr.parent
  SET administrative_center = tmp.Capital;');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
