<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140205111047 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
                CREATE TABLE support_topic (
                            id INT AUTO_INCREMENT NOT NULL,
                            author_id INT DEFAULT NULL,
                            company_id INT DEFAULT NULL,
                            created_at DATETIME NOT NULL,
                            title VARCHAR(255) NOT NULL,
                            description VARCHAR(255) NOT NULL,
                            answers_count SMALLINT DEFAULT '0' NOT NULL,
                            unread_answers_count SMALLINT DEFAULT '0' NOT NULL,
                            last_answer_at DATETIME NOT NULL,
                            INDEX IDX_6FFAC8C3F675F31B (author_id),
                            INDEX IDX_6FFAC8C3979B1AD6 (company_id),
                            PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;");

        $this->addSql("
                CREATE TABLE support_answer (
                              id INT AUTO_INCREMENT NOT NULL,
                              topic_id INT DEFAULT NULL,
                              author_id INT DEFAULT NULL,
                              created_at DATETIME NOT NULL,
                              message VARCHAR(255) NOT NULL,
                              INDEX IDX_5227AAD51F55203D (topic_id),
                              INDEX IDX_5227AAD5F675F31B (author_id),
                              PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;");

        $this->addSql("ALTER TABLE support_answer ADD CONSTRAINT FK_5227AAD51F55203D FOREIGN KEY (topic_id) REFERENCES support_topic (id);");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
