<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140228174018 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('UPDATE agreement_template SET content = "{{ brouzie_render_widget(\'MetalCorpsiteBundle:Feedback\') }}<span class=\"js-popup-opener link clickable\" data-popup=\"#feedback-popup\">Добавить отзыв</span>"');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
    }
}
