<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140227123734 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("INSERT INTO agreement_template VALUES (3, 'О компании', '')");
        $this->addSql("INSERT INTO agreement_template VALUES (4, 'Контакты', '')");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
