<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140213201110 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE support_topic ADD resolved_by INT DEFAULT NULL, ADD resolved_at DATETIME DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_6FFAC8C357EB21F9 ON support_topic (resolved_by)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
