<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140207220535 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE support_topic ADD last_answer_id INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6FFAC8C3BDFC9701 ON support_topic (last_answer_id)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
