<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140225170620 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        if ($schema->getTable('Message142')->hasColumn('Memo2Title')) {
            return;
        }

        $this->addSql("ALTER TABLE Message142 ADD Memo2Title TINYINT(1) DEFAULT '0' NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
