<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140214150035 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE callback ADD processed_by INT DEFAULT NULL, ADD processed_at DATETIME DEFAULT NULL, ADD notation VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_79F97426888A646A ON callback (processed_by)');

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
