<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140227135841 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE agreement_template ADD replacements LONGTEXT NOT NULL;');
        $description =<<<HTML
шаблоны подстановок:
{{ company.title }} - название компании
{{ company.companyType.title }} - форма собственности компании
{{ paymentDetails.nameOfLegalEntity }} - наименование юридического лица
{{ paymentDetails.inn }} - идентификационный код
{{ paymentDetails.kpp }} - кпп
{{ paymentDetails.ogrn }} - ОГРН
{{ paymentDetails.director }} - ФИО руководителя
{{ paymentDetails.mailAddress }} - почтовый адрес
{{ paymentDetails.legalAddress}} - юридический адрес
{{ paymentDetails.rs }} - номер р/счета в рублях
{{ paymentDetails.corpBill }} - номер корп. счета
{{ paymentDetails.bik}} - БИК банка
{{ paymentDetails.bank }} - наименование банка
HTML;

        $this->addSql("UPDATE agreement_template SET replacements = :description WHERE id = 1", array('description' => $description));
        $this->addSql("UPDATE agreement_template SET replacements = '' WHERE id = 2");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
